# Generated by Django 5.2.8 on 2026-01-31 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_userarticleinteraction_clicked_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
